services:
  blue:
    container_name: blue
    image: gvf156/yapp-dev:latest
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - TZ=Asia/Seoul
    restart: always
    ports:
      - "8081:8080"
  green:
    container_name: green
    image: gvf156/yapp-dev:latest
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - TZ=Asia/Seoul
    restart: always
    ports:
      - "8082:8080"
