spring:
  application:
    name: yapp

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://34.64.95.166:3306/brake_prod?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: stop123!

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none

  data:
    redis:
      host: brake-redis-prod
      port: 6379
      repositories:
        enabled: false

  flyway:
    enabled: true
    baseline-on-migrate: true
    out-of-order: true

jwt:
  secret: 1QceuL7TSKpfbS+oFH0AkTO162ufYKCe7Byig0N8+chtyUQKzu8FqLVIoJI8fAuoFbpE1HdKeHcaukWWMJdiKA==
  access-token-expiry-time: 1800
  refresh-token-expiry-time: 1209600

cors:
  allowed-origins: "https://brake.r-e.kr,http://localhost:*"

oauth:
  kakao:
    client-id: 7f12d6e55848a7d52189a82f69a97df5
    client-secret: Kpjwpgm7tKdVHhXT5j4q6kupT3m3HWWH
    redirect-uri: https://www.brake/oauth
    admin-key: d7c3e9f495d113bf66e4ca421b5871b5
  apple:
    client-id: yapp.breake
    team-id: DX6WKZY687
    key-id: DG4C5SZ4ZX
    audience: https://appleid.apple.com
    auth-key-path: file:/YAPP-ENV/AuthKey_DG4C5SZ4ZX.p8

management:
  endpoints:
    web:
      exposure:
        include: prometheus,metrics,health
  endpoint:
    metrics:
      access: read_only
server:
  tomcat:
    mbeanregistry:
      enabled: true

logging:
  config: classpath:/log/logback-prod.xml
