spring:
  profiles:
    active: test

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=MySQL;
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
  flyway:
    enabled: false

oauth:
  kakao:
    client-id: asndlkasda
    client-secret: clientsecretclientsecret
    redirect-uri: ajsdkasdasdjalsd
    admin-key: adminkeyadminkey
  apple:
    client-id: yapyapyap
    team-id: myteam
    key-id: mykey
    audience: myaudience
    auth-key-path: mykeypath

jwt:
  secret: abcdefghijklmnopqrstuvwxyz0123456789abcdefghijklmnopqrstuvwxyz0123456789
  access-token-expiry-time: 1800
  refresh-token-expiry-time: 1209600

cors:
  allowed-origins: "http://localhost:*"
